apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: rec-sys
stringData:
  sql: |
    path: postgresql+psycopg://${user}:${password}@${host}:${port}/${dbname}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
  postgres: |
    host: ${host}
    port: 5432
    database: ${dbname}
    db_schema: public
    user: ${user}
    password: ${password}
    # sslmode: verify-full
    # sslkey_path: /var/lib/postgresql/certs/tls.key
    # sslcert_path: /var/lib/postgresql/certs/tls.crt
    # sslrootcert_path: system
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: feast-edb-rec-sys
  namespace: rec-sys
spec:
  feastProject: feast_edb_rec_sys
  feastProjectDir:
    git:
      url: https://github.com/RHEcosystemAppEng/rec-sys-app
      ref: main
  services:
    offlineStore:
      persistence:
        file:
          type: duckdb
      server:
        env:
          - name: MPLCONFIGDIR
            value: /tmp
        envFrom:
          - secretRef:
              name: cluster-sample-app
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: cluster-sample-app
        env:
        - name: MPLCONFIGDIR
          value: /tmp
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          env:
            - name: MPLCONFIGDIR
              value: /tmp
          envFrom:
            - secretRef:
                name: cluster-sample-app
    ui:
      envFrom:
        - secretRef:
            name: cluster-sample-app