apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: feast
stringData:
  sql: |
    path: postgresql+psycopg://${USER}:${PASSWORD}@${HOST}:${PORT}/${DBNAME}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: feast-edb-rec-sys
spec:
  feastProject: feast_edb_rec_sys
  feastProjectDir:
    git:
      url: https://github.com/RHEcosystemAppEng/rec-sys-feast-repository
      ref: main
  services:
    offlineStore:
      persistence:
        file:
          type: duckdb
    onlineStore:
      persistence:
        store:
          type: sql
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: vectordb-app
        env:
        - name: MPLCONFIGDIR
          value: /tmp
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores # TODO why the registry and the onlinestore pointing to the same dbname?