apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.app }}
  namespace: {{ .Values.global.recsys.namespace }}
spec:
  selector:
    app: {{ .Values.kafka.app }}
  ports:
    - protocol: {{ .Values.kafka.service.protocol }}
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}