apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: connect-cluster
  name: source-connector-new-users
  namespace: {{ .Values.kafka.namespace }}
spec:
  class: io.aiven.connect.jdbc.JdbcSinkConnector
  config:
    value.converter: org.apache.kafka.connect.json.JsonConverter
    topics: new-users
    value.converter.schemas.enable: true
    connection.password: "${secrets:rec-sys/cluster-sample-app:password}"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    batch.size: 3
    pk.mode: none
    insert.mode: insert
    table.name.format: new_users
    connection.user: "${secrets:rec-sys/cluster-sample-app:user}"
    auto.create: true
    auto.evolve: true
    key.converter.schemas.enable: false
    connection.url: "${secrets:rec-sys/cluster-sample-app:jdbc-uri}"
    transforms: "TimestampConverter"
    transforms.TimestampConverter.type: "org.apache.kafka.connect.transforms.TimestampConverter$Value"
    transforms.TimestampConverter.format: "YYYY-MM-DD hh:mm:ss.s"
    transforms.TimestampConverter.target.type: "Timestamp"
    transforms.TimestampConverter.field: "timestamp"
  tasksMax: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: connect-cluster
  name: source-connector-interactions
  namespace: {{ .Values.kafka.namespace }}
spec:
  class: io.aiven.connect.jdbc.JdbcSinkConnector
  config:
    value.converter: org.apache.kafka.connect.json.JsonConverter
    topics: interactions
    value.converter.schemas.enable: true
    connection.password: "${secrets:rec-sys/cluster-sample-app:password}"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    batch.size: 3
    pk.mode: none
    insert.mode: insert
    table.name.format: stream_interaction
    connection.user: "${secrets:rec-sys/cluster-sample-app:user}"
    auto.create: true
    auto.evolve: true
    key.converter.schemas.enable: false
    connection.url: "${secrets:rec-sys/cluster-sample-app:jdbc-uri}"
    transforms: "TimestampConverter"
    transforms.TimestampConverter.type: "org.apache.kafka.connect.transforms.TimestampConverter$Value"
    transforms.TimestampConverter.format: "YYYY-MM-DD hh:mm:ss.s"
    transforms.TimestampConverter.target.type: "Timestamp"
    transforms.TimestampConverter.field: "timestamp"
  tasksMax: 1