apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: connect-cluster
  namespace: {{ .Values.kafka.namespace }}
spec:
  bootstrapServers: '{{ .Values.kafka.cluster.name }}-kafka-bootstrap.kafka.svc.cluster.local:9093'
  build:
    output:
      image: 'image-registry.openshift-image-registry.svc:5000/rec-sys/connect-cluster:latest'
      type: docker
    plugins:
      - artifacts:
          - type: zip
            url: 'https://github.com/Aiven-Open/jdbc-connector-for-apache-kafka/releases/download/v6.10.0/jdbc-connector-for-apache-kafka-6.10.0.zip'
        name: jdbc
  config:
    config.storage.replication.factor: -1
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    offset.storage.replication.factor: -1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: -1
    status.storage.topic: connect-cluster-status
  replicas: 1
  tls:
    trustedCertificates:
      - pattern: '*.crt'
        secretName: {{ .Values.kafka.cluster.name }}-cluster-ca-cert
  version: 4.0.0