apiVersion: v1
kind: Secret
metadata:
  name: jary-myconnectbot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhbUZ5ZVN0dGVXTnZibTVsWTNSaWIzUTZOemhJV1U1SE56QlZTbFpWTlVZeVZsRklVemc1UzA0eVNEazBXVFJOUWtwQ1NGZFRUVVphTkZBMVdEUkxUVkpYVERZNE5rTkNNVU5STVRBNFJVOVZSZz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson